version: '3'
services:
  app:
    build:
     context: .
     dockerfile: php/Dockerfile
    volumes:
       - ./lumen_app/:/var/www/app/
  # tty: true
  # command: '/bin/sh'
  web:
    build:
     context: .
     dockerfile: nginx/Dockerfile
    volumes:
       - ./lumen_app:/var/www/app/  
    ports:
       - "127.0.2.2:8080:80"
